### ISSUE TITLE
Certain multi line ais do not decode correctly.

### ISSUE THREAD

**Issue by Oritide** [fulup-bzh/GeoGate#20] opened 2017-03-07 14:16 UTC
Just had a ship go by that sent this message:
```
!AIVDM,2,1,9,A,53Moi:81Qk8LLpQH000PD98T@D4r118Tp<E=<0153@f594ke07TSm21D,0*63
!AIVDM,2,2,9,A,hF@000000000000,2*73
```
Unfortunately the decoder seemed to ignore a lot of the data and only output this:
```
AisDecode {
  bitarray: [],
  valid: false,
  payload: <Buffer 35 33 4d 6f 69 3a 38 31 51 6b 38 4c 4c 70 51 48 30 30 30 50 44 39 38 54 40 44 34 72 31 31 38 54 70 3c 45 3d 3c 30 31 35 33 40 66 35 39 34 6b 65 30 37 ... >,
  msglen: 56,
  channel: 'A' }
AisDecode {
  bitarray:
   [ 133, 131, 157, 183, 177, 138, 136, 129, 161, 179, 136, 156, 156, 184, 161, 152, 128, 128, 128, 160, 148, 137, 136, 164, 144, 148, 132, 186, 129, 129, 136, 164, 184, 140, 149, 141, 140, 128, 129, 133, 131, 144, 174, 133, 137, 132, 179, 173, 128, 135, 164, 163, 181, 130, 129, 148, 176, 150, 144, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128 ],
  valid: false,
  payload: <Buffer 35 33 4d 6f 69 3a 38 31 51 6b 38 4c 4c 70 51 48 30 30 30 50 44 39 38 54 40 44 34 72 31 31 38 54 70 3c 45 3d 3c 30 31 35 33 40 66 35 39 34 6b 65 30 37 ... >,
  msglen: 71,
  channel: 'A',
  aistype: 5,
  repeat: 0,
  mmsi: '232649000',
  class: 'A' }
```

**Comment by fulup-bzh** [comment] 2017-03-07 14:28
If this is a multi-frame message you need to let the decoder do not forget that you should provide a session object to store multi-part messages "Function AisDecode (input, session)"

See comment on https://github.com/SignalK/signalk-parser-nmea0183/issues/32

**Comment by Oritide** [comment] 2017-03-07 14:34
@fulup-bzh I have a object for storing session and have had it work for all other multi line messages this is the first that has not worked

**Comment by fulup-bzh** [comment] 2017-03-07 14:37
Then we have a bug, if you have a fix to propose, I would be more than happy to include it.

**Comment by Oritide** [comment] 2017-03-07 16:37
Here is another one that doesn't decode fully from a different ship:
```
!AIVDM,2,1,6,A,53n>Nv82E:?thA<b2218tp`61=E10u9@E:2222162@e754rdR>0j0CQC,0*33
!AIVDM,2,2,6,A,8<M`1Sl`11Dm2CP,2*5D
```
I Think I have had this ship here before and it decoded fully unfortunately I did not save the message

**Comment by fulup-bzh** [comment] 2017-03-07 16:53
Next time please store the message so we may reproduce the error.

**Comment by Oritide** [comment] 2017-03-07 18:07
I have done some testing and it seems to be the AIS_version_indicator is not less than 2. at line 309:             `if( AIS_version_indicator < 2 ) {` setting it to 3 makes it work not sure if this causes any issues elsewhere?

**Comment by fulup-bzh** [comment] 2017-03-07 18:13
Well done, would need to check in the spec to understand what this is. I must say that I do not remember why I placed it to "2". Any idea what this indicator is ?

**Comment by Oritide** [comment] 2017-03-07 18:14
Not sure your comments say:
//          Get the AIS Version indicator
//          0 = station compliant with Recommendation ITU-R M.1371-1
//          1 = station compliant with Recommendation ITU-R M.1371-3
//          2-3 = station compliant with future editions

**Comment by Oritide** [comment] 2017-03-07 18:16
guessing the ships are using a slightly newer AIS Version and this was coded when it was only version 2?

**Comment by Oritide** [comment] 2017-03-07 18:23
yeah looks like that has been updated 
https://www.navcen.uscg.gov/?pageName=AISMessagesAStatic
says:
AIS version indicator
0 = station compliant with Recommendation ITU-R M.1371-1
1 = station compliant with Recommendation ITU-R M.1371-3 (or later)
2 = station compliant with Recommendation ITU-R M.1371-5 (or later)
3 = station compliant with future editions

**Comment by fulup-bzh** [comment] 2017-03-07 18:38
It looks like we could just ignore this value, don't you think so ?

**Comment by Oritide** [comment] 2017-03-07 18:40
I think so just look like it is to say the are compliant with certain recommendations

**Comment by fulup-bzh** [comment] 2017-03-07 18:42
If you move it out with a comment, I will merge your proposal.

**Comment by afischerdev** [comment] 2017-03-14 19:55
I add a pull request. Hope to be not to fast with this.

**Comment by fulup-bzh** [comment] 2017-03-20 08:49
Oritide I think this might be closed now, isn't it ? As you open it, I leave you to close it.

**Closed** 2017-03-20 12:05 UTC
